
        thisdir = fileparts( mfilename( 'fullpath' ) );
        addpath( thisdir,...
                [thisdir filesep 'BFMatlab'],...  
                [thisdir filesep 'Classes'],...            
                [thisdir filesep 'matlab_code'],...
                [thisdir filesep 'matlab_code' filesep 'dpc_functions'],...
                [thisdir filesep 'minFunc'],...
                [thisdir filesep 'minFunc' filesep 'minFunc'],...
                [thisdir filesep 'minFunc' filesep 'minFunc' filesep 'compiled'],...
                [thisdir filesep 'minFunc' filesep 'minFunc' filesep 'mex'],...
                [thisdir filesep 'minFunc' filesep 'autoDif'],...
                [thisdir filesep 'minFunc' filesep 'logisticExample'],...
                [thisdir filesep 'sample_data']);
